#ifndef CONFIG_H
#define CONFIG_H

#define LIGHT_NODE_I2C_PORT i2c0
#define LIGHT_NODE_I2C_SDA_PIN 0
#define LIGHT_NODE_I2C_SCL_PIN 1
#define LIGHT_NODE_I2C_BAUDRATE 100000

#define BH1750_I2C_ADDRESS 0x23

#define WS2812_DATA_PIN 2
/* 長燈條版本預設：300 顆 LED。若實際燈條顆數不同，請只修改 WS2812_LED_COUNT。 */
#define WS2812_LED_COUNT 300
#define WS2812_PIO_INSTANCE pio0
#define WS2812_SM 0
#define WS2812_DEFAULT_BRIGHTNESS 64

#define SENSOR_READ_INTERVAL_MS 1000

#define LIGHT_NODE_ID "bedroom01"
#define LIGHT_NODE_VERSION "1.2.1-reliability"

#define BRIGHTNESS_PCT_MIN 0
#define BRIGHTNESS_PCT_MAX 100
#define TRANSITION_DEFAULT_ENABLED 1
#define AUTO_MIN_SWITCH_INTERVAL_MS 800u
#define ADAPTIVE_SENSOR_TIMEOUT_MS 3000u
#define FLOW_SOFT_MODE_BRIGHTNESS_MAX_PCT 60

/* MCU Watchdog：用於主迴圈卡死、I2C/LED 更新異常時自動重啟。 */
#define LIGHT_NODE_WATCHDOG_ENABLE 1
#define LIGHT_NODE_WATCHDOG_TIMEOUT_MS 5000u

/* tone_bias 共用範圍：scene 與 auto 共用同一套色溫偏移邏輯。 */
#define LIGHT_NODE_TONE_BIAS_MIN (-2)
#define LIGHT_NODE_TONE_BIAS_MAX 2

/* Kelvin 色溫控制：供 Web 色溫滑桿與 Server 對接使用。 */
#define COLOR_TEMP_K_MIN 2700
#define COLOR_TEMP_K_MAX 6500
#define COLOR_TEMP_K_DEFAULT 3900
#define COLOR_TEMP_K_NONE 0

/* Scene 預設色溫，僅用於 status 與 color_temp_k 未覆寫時的語意回報。 */
#define SCENE_SLEEP_COLOR_TEMP_K 2700
#define SCENE_RELAX_COLOR_TEMP_K 3000
#define SCENE_WORK_COLOR_TEMP_K 4500
#define SCENE_EXERCISE_R 255
#define SCENE_EXERCISE_G 120
#define SCENE_EXERCISE_B 40

#define SCENE_SLEEP_TARGET_LUX 50
#define SCENE_SLEEP_TOLERANCE_LUX 20
#define SCENE_SLEEP_MIN_OUTPUT_PCT 0
#define SCENE_SLEEP_MAX_OUTPUT_PCT 30
#define SCENE_RELAX_TARGET_LUX 250
#define SCENE_RELAX_TOLERANCE_LUX 50
#define SCENE_RELAX_MIN_OUTPUT_PCT 5
#define SCENE_RELAX_MAX_OUTPUT_PCT 70
#define SCENE_WORK_TARGET_LUX 500
#define SCENE_WORK_TOLERANCE_LUX 75
#define SCENE_WORK_MIN_OUTPUT_PCT 0
#define SCENE_WORK_MAX_OUTPUT_PCT 100
#define SCENE_EXERCISE_TARGET_LUX 400
#define SCENE_EXERCISE_TOLERANCE_LUX 100
#define SCENE_EXERCISE_MIN_OUTPUT_PCT 10
#define SCENE_EXERCISE_MAX_OUTPUT_PCT 85

#define AUTO_LIGHT_LUX_MIN 0.0f
#define AUTO_LIGHT_LUX_MAX 2000.0f
#define AUTO_LIGHT_ZONE1_MAX_LUX 20.0f
#define AUTO_LIGHT_ZONE2_MAX_LUX 60.0f
#define AUTO_LIGHT_ZONE3_MAX_LUX 120.0f
#define AUTO_LIGHT_ZONE4_MAX_LUX 250.0f
#define AUTO_SENSOR_TIMEOUT_MS 5000u
#define AUTO_SENSOR_MAX_LUX 100000.0f
#define AUTO_LIGHT_EMA_ALPHA 0.35f
#define AUTO_LIGHT_EMA_OLD_WEIGHT 0.65f

/* Auto 模式輸出表：避免 auto_light_service.c 寫死亮度與色溫。
 * Zone1 代表環境最暗，Zone5 代表環境最亮。
 * auto 會依 lux 區間同步調整 brightness_pct 與 color_temp_k。
 */
#define AUTO_LIGHT_ZONE1_BRIGHTNESS_PCT 100
#define AUTO_LIGHT_ZONE2_BRIGHTNESS_PCT 85
#define AUTO_LIGHT_ZONE3_BRIGHTNESS_PCT 65
#define AUTO_LIGHT_ZONE4_BRIGHTNESS_PCT 40
#define AUTO_LIGHT_ZONE5_BRIGHTNESS_PCT 15
#define AUTO_LIGHT_ZONE1_COLOR_TEMP_K 2700
#define AUTO_LIGHT_ZONE2_COLOR_TEMP_K 3000
#define AUTO_LIGHT_ZONE3_COLOR_TEMP_K 3900
#define AUTO_LIGHT_ZONE4_COLOR_TEMP_K 4200
#define AUTO_LIGHT_ZONE5_COLOR_TEMP_K 5000

#define LED_TRANSITION_COLOR_STEP 3
#define LED_TRANSITION_BRIGHTNESS_STEP 3
#define LED_TRANSITION_UPDATE_INTERVAL_MS 20u

#define LIGHT_NODE_UART_ID uart1
#define LIGHT_NODE_UART_BAUDRATE 115200
#define LIGHT_NODE_UART_TX_PIN 4
#define LIGHT_NODE_UART_RX_PIN 5
#define LIGHT_NODE_UART_IRQ UART1_IRQ

#define UART_COMM_RX_RING_SIZE 512
#define UART_COMM_LINE_BUFFER_SIZE 256
#define UART_COMM_TX_LINE_MAX 512
#define UART_COMM_TX_QUEUE_DEPTH 16

/* FLOW mode 參數 */
#define FLOW_DEFAULT_BRIGHTNESS 96
#define FLOW_DEFAULT_SPEED 48
#define FLOW_UPDATE_INTERVAL_MS 25

/* USB 偵錯鏡像開關 */
#define LIGHT_NODE_USB_STATUS_MIRROR 0
#define LIGHT_NODE_USB_EVENT_MIRROR 1
#define LIGHT_NODE_USB_READY_MIRROR 1

/* 編譯期防呆：避免硬體 pin 設定互相衝突。 */
_Static_assert(WS2812_LED_COUNT > 0, "WS2812_LED_COUNT must be greater than 0");
_Static_assert(WS2812_DATA_PIN != LIGHT_NODE_I2C_SDA_PIN, "WS2812_DATA_PIN conflicts with I2C SDA pin");
_Static_assert(WS2812_DATA_PIN != LIGHT_NODE_I2C_SCL_PIN, "WS2812_DATA_PIN conflicts with I2C SCL pin");
_Static_assert(WS2812_DATA_PIN != LIGHT_NODE_UART_TX_PIN, "WS2812_DATA_PIN conflicts with UART TX pin");
_Static_assert(WS2812_DATA_PIN != LIGHT_NODE_UART_RX_PIN, "WS2812_DATA_PIN conflicts with UART RX pin");
_Static_assert(LIGHT_NODE_I2C_SDA_PIN != LIGHT_NODE_I2C_SCL_PIN, "I2C SDA and SCL pins must be different");
_Static_assert(LIGHT_NODE_UART_TX_PIN != LIGHT_NODE_UART_RX_PIN, "UART TX and RX pins must be different");
_Static_assert(LIGHT_NODE_I2C_SDA_PIN != LIGHT_NODE_UART_TX_PIN, "I2C SDA conflicts with UART TX pin");
_Static_assert(LIGHT_NODE_I2C_SDA_PIN != LIGHT_NODE_UART_RX_PIN, "I2C SDA conflicts with UART RX pin");
_Static_assert(LIGHT_NODE_I2C_SCL_PIN != LIGHT_NODE_UART_TX_PIN, "I2C SCL conflicts with UART TX pin");
_Static_assert(LIGHT_NODE_I2C_SCL_PIN != LIGHT_NODE_UART_RX_PIN, "I2C SCL conflicts with UART RX pin");
_Static_assert(LIGHT_NODE_WATCHDOG_TIMEOUT_MS >= 1000u, "WATCHDOG timeout should be at least 1000 ms");
_Static_assert(LIGHT_NODE_WATCHDOG_TIMEOUT_MS <= 8000u, "WATCHDOG timeout should not exceed RP2040 practical limit");
_Static_assert(AUTO_LIGHT_ZONE1_BRIGHTNESS_PCT >= BRIGHTNESS_PCT_MIN && AUTO_LIGHT_ZONE1_BRIGHTNESS_PCT <= BRIGHTNESS_PCT_MAX, "AUTO zone1 brightness out of range");
_Static_assert(AUTO_LIGHT_ZONE2_BRIGHTNESS_PCT >= BRIGHTNESS_PCT_MIN && AUTO_LIGHT_ZONE2_BRIGHTNESS_PCT <= BRIGHTNESS_PCT_MAX, "AUTO zone2 brightness out of range");
_Static_assert(AUTO_LIGHT_ZONE3_BRIGHTNESS_PCT >= BRIGHTNESS_PCT_MIN && AUTO_LIGHT_ZONE3_BRIGHTNESS_PCT <= BRIGHTNESS_PCT_MAX, "AUTO zone3 brightness out of range");
_Static_assert(AUTO_LIGHT_ZONE4_BRIGHTNESS_PCT >= BRIGHTNESS_PCT_MIN && AUTO_LIGHT_ZONE4_BRIGHTNESS_PCT <= BRIGHTNESS_PCT_MAX, "AUTO zone4 brightness out of range");
_Static_assert(AUTO_LIGHT_ZONE5_BRIGHTNESS_PCT >= BRIGHTNESS_PCT_MIN && AUTO_LIGHT_ZONE5_BRIGHTNESS_PCT <= BRIGHTNESS_PCT_MAX, "AUTO zone5 brightness out of range");

_Static_assert(COLOR_TEMP_K_MIN < COLOR_TEMP_K_MAX, "COLOR_TEMP_K_MIN must be less than COLOR_TEMP_K_MAX");
_Static_assert(COLOR_TEMP_K_DEFAULT >= COLOR_TEMP_K_MIN && COLOR_TEMP_K_DEFAULT <= COLOR_TEMP_K_MAX, "COLOR_TEMP_K_DEFAULT out of range");
_Static_assert(SCENE_SLEEP_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && SCENE_SLEEP_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "sleep color temp out of range");
_Static_assert(SCENE_RELAX_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && SCENE_RELAX_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "relax color temp out of range");
_Static_assert(SCENE_WORK_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && SCENE_WORK_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "work color temp out of range");
_Static_assert(AUTO_LIGHT_ZONE1_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && AUTO_LIGHT_ZONE1_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "AUTO zone1 color temp out of range");
_Static_assert(AUTO_LIGHT_ZONE2_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && AUTO_LIGHT_ZONE2_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "AUTO zone2 color temp out of range");
_Static_assert(AUTO_LIGHT_ZONE3_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && AUTO_LIGHT_ZONE3_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "AUTO zone3 color temp out of range");
_Static_assert(AUTO_LIGHT_ZONE4_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && AUTO_LIGHT_ZONE4_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "AUTO zone4 color temp out of range");
_Static_assert(AUTO_LIGHT_ZONE5_COLOR_TEMP_K >= COLOR_TEMP_K_MIN && AUTO_LIGHT_ZONE5_COLOR_TEMP_K <= COLOR_TEMP_K_MAX, "AUTO zone5 color temp out of range");

#endif
